import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import CE_Navbar from "@/components/layout/navigation/client.navigation";

const IbmPlexSans = IBM_Plex_Sans({
    subsets: ["latin"],
    variable: "--font-alumni-sans",
    weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Housing Landing App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={IbmPlexSans.className}>
                <CE_Navbar />
                {children}
            </body>
        </html>
    );
}
